### PR TITLE
Add gallery feature

### PR DESCRIPTION
**Pull request by mgeier**
See  #254.

A few minor things are still missing, but most of it should be working already.

Loading the styles from Sphinx-Gallery should become simpler with this: https://github.com/sphinx-gallery/sphinx-gallery/pull/601.

Rendered HTML: https://130-210404706-gh.circle-artifacts.com/0/html/subdir/gallery.html

### CODE REVIEW

**Comment by mgeier** [comment]
I've asked at the Sphinx mailing list (https://groups.google.com/d/topic/sphinx-dev/Jh42WXO-mHo/discussion) and have added 7f2c842e6f32994cd6ab032735b6e2df491feda7 based on the answer I got there.

**Comment by mgeier** [comment]
Updated rendered version:

* https://140-210404706-gh.circle-artifacts.com/0/html/subdir/gallery.html
* https://140-210404706-gh.circle-artifacts.com/0/html/a-normal-rst-file.html#thumbnail-galleries

**Comment by mgeier** [comment]
Updated rendered version:

* https://148-210404706-gh.circle-artifacts.com/0/html/subdir/gallery.html
* https://148-210404706-gh.circle-artifacts.com/0/html/a-normal-rst-file.html#thumbnail-galleries

**Comment by mgeier** [comment]
Updated rendered version:

* https://148-210404706-gh.circle-artifacts.com/0/html/subdir/gallery.html
* https://148-210404706-gh.circle-artifacts.com/0/html/a-normal-rst-file.html#thumbnail-galleries

**Comment by mgeier** [comment]
Sphinx-Gallery 0.6.0 has just been released, now this is ready for review!

Rendered:

* https://180-210404706-gh.circle-artifacts.com/0/html/subdir/gallery.html
* https://180-210404706-gh.circle-artifacts.com/0/html/a-normal-rst-file.html#thumbnail-galleries
* https://180-210404706-gh.circle-artifacts.com/0/nbsphinx.pdf#section.11
* https://180-210404706-gh.circle-artifacts.com/0/nbsphinx.pdf#subsection.13.7

**Comment by maartenbreddels** [comment]
Hi Matthias,

this seems to work really well!
I plan to manually take screenshots/screen captures of ipyvolume. I'd like to thus manually add the thumbnail. If I do this in conf.py, I cannot add a tooltip. Would it be an idea to add this as well, .e.g:
```
nbsphinx_thumbnails = {
    'examples/scatter': 'examples/scatter.png',
    'examples/volshow': {'filename': 'examples/scatter.png', 'tooltip': 'Basic volume,
}
```

Even better would be if we could auto generate a tooltip from the 1st markdown cell, the first sentence after the first H1 (i guess that is what sphinx-gallery does).

cheers,

Maarten

**Comment by mgeier** [comment]
Thanks @maartenbreddels for testing this!

I've merged this in order for other people to be able to make PRs with further improvements.

I've moved your above comment to a new issue: #421.

**Pull request merged**
