### PR TITLE
Copy locally linked files only for Jupyter notebooks

### PR DESCRIPTION
**Pull request by mgeier**
... while still re-writing local links to Sphinx source files in all
Sphinx source files (not only notebooks).

See also #174.

### CODE REVIEW

**Comment by mgeier** [comment]
A bit more explanation:

I split up `ProcessLocalLinks` into two parts: `RewriteLocalLinks` and `CopyLinkedFiles`.
This way, I can apply the former to all Sphinx source files, while the latter is only applied to Jupyter notebooks.

**Comment by jschueller** [comment]
Is a release planned after this gets merged ?

**Comment by mgeier** [comment]
Thanks @jschueller for testing!

> Is a release planned after this gets merged ?

Yes, definitely. I also want to merge #179 and then I want to wait for a few days for people to test it in the `master` branch.
If you see more than a week of inactivity, please remind me ...

**Comment by jschueller** [comment]
Ok, thanks.

**Pull request merged**
