### PR TITLE
Avoid using the broken Sphinx version 1.5

### PR DESCRIPTION
**Pull request by mgeier**
See #77 and #78.

This should be merged as soon as Sphinx 1.5.1 (which hopefully fixes https://github.com/sphinx-doc/sphinx/pull/3224) is released.

### CODE REVIEW

**Comment by SylvainCorlay** [comment]
+1

**Comment by michaelpacer** [comment]
1.5.1 is released!

**Comment by michaelpacer** [comment]
Unfortunately, I don't think it solves the problem :/ as when I explicitly use 1.5.1 in RTD, I'm still getting an error from `depart_code_latex`.

**Comment by michaelpacer** [comment]
Oh, that update is delayed until 1.5.2 now, which means this will remain broken for another month.

**Comment by mgeier** [comment]
If #85 fixes #78, I can merge this now, right?

**Comment by mgeier** [comment]
... and then I could make a new `nbsphinx` release in the next few days.

**Comment by michaelpacer** [comment]
Yes!

**Pull request merged**
