### PR TITLE
switch Node.traverse() to findall() to avoid deprecation warnings

### PR DESCRIPTION
**Pull request by wpbonelli**
This should be OK to switch straight to `.findall()` with no need to try/except and fall back to `.traverse()` since [sphinx requires docutils >= 0.18.1](https://github.com/sphinx-doc/sphinx/blob/2f6ea1422b08f9494f34b80c2ff6c96b5f396fdc/pyproject.toml#L66)

### CODE REVIEW

**Comment by mgeier** [comment]
Thanks for this PR, and sorry for my very late response!

Before merging this, I would like to check which versions I want to support and re-activate the tests, see #495.

For now, I have silenced the warning (a1a56f517fed1a2e068cf4e52a34c4c5afbf8121), which can be reverted once this is merged.

**Comment by mgeier** [comment]
I have finally checked which versions I want to support and I have re-activated the tests in #792.

Can you please re-base your PR and add a lower bound to our `docutils` dependency?

https://github.com/spatialaudio/nbsphinx/blob/c5fbe13c61f9a9f17bb6ea90c00f7624082665c4/setup.py#L27

**Comment by wpbonelli** [comment]
@mgeier sure! done.

**Comment by mgeier** [comment]
Thanks a lot!

**Pull request merged**
